;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-paste
        mouse-minor-mode-menu
        xah-backward-kill-word
        xah-fly-command-mode-activate-no-hook
        xah-fly-insert-mode-activate
        ))

(setq mc/cmds-to-run-once
      '(
        xah-delete-backward-char-or-bracket-text
        ))
